global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using Microsoft.AspNetCore.Mvc;
global using SOP.Controllers;
global using SOP.Database;
global using SOP.Entities;
global using SOP.Repositories;
global using SOP.DTOs;
global using SOP.Authentication;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.IdentityModel.Tokens;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using Microsoft.OpenApi.Models;
global using SOP.Helpers;
global using SOP.Authorization;
global using AllowAnonymousAttribute = SOP.Authorization.AllowAnonymousAttribute;
global using AuthorizeAttribute = SOP.Authentication.AuthorizeAttribute;
//global using OtpNet;
global using SOP.Archive.Entities;
global using System.Data;
global using SOP.Archive.Repository;
global using Microsoft.AspNetCore.Cors;
global using SOP.Encryption;
global using SOP.Archive.DTOs;